name: Repository-Variables-Secrets
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Access-Repo-Variable
        run: echo ${{vars.USERNAME}}
      - name: Access-Repo-SECRET
        run: echo ${{secrets.PASSWORD}}
